/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2021-03-12 08:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equlv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>后台管理页面</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/index.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function mouseoveMessage(e){\r\n");
      out.write("        \tclearTimeout(time);\r\n");
      out.write("            var ulDNoneGoods=document.getElementById(e);\r\n");
      out.write("            ulDNoneGoods.style.display='block'\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("        function mouseleaveMessage(e){\r\n");
      out.write("        \ttime = setTimeout(function(){//这个区域放置1-2秒，而不是 只要划过就行\r\n");
      out.write("                var ulDNoneGoods=document.getElementById(e);\r\n");
      out.write("                ulDNoneGoods.style.display='none'\r\n");
      out.write("        \t},1000)\r\n");
      out.write("        }\r\n");
      out.write("        function mouseoveTypes(e){\r\n");
      out.write("        \tclearTimeout(time);\r\n");
      out.write("            var ulDNoneGoods=document.getElementById(e);\r\n");
      out.write("            ulDNoneGoods.style.display='block'\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("        function mouseleaveTypes(e){\r\n");
      out.write("        \ttime = setTimeout(function(){//这个区域放置1-2秒，而不是 只要划过就行\r\n");
      out.write("                var ulDNoneGoods=document.getElementById(e);\r\n");
      out.write("                ulDNoneGoods.style.display='none'\r\n");
      out.write("        \t},1000)\r\n");
      out.write("        }\r\n");
      out.write("/*        function mouseoverDispayBox(){\r\n");
      out.write("            var boxcont1=document.getElementById('boxcont1');\r\n");
      out.write("            boxcont1.style.display='none'\r\n");
      out.write("        }\r\n");
      out.write("        function mouseleaveDispayBox(){\r\n");
      out.write("            \r\n");
      out.write("        }*/\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class=\"layer clearfix\">\r\n");
      out.write("\t\t<h1>欢迎您进入后台管理页面</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"nav\"  class=\"layer clearfix\">\r\n");
      out.write("\t\t<ul class=\"ulD\" >\r\n");
      out.write("\t\t\t<li class=\"liD\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"navCM\" onmouseover=\"mouseoveMessage('ulDNoneGoods')\" onmouseleave=\"mouseleaveMessage('ulDNoneGoods')\">商品管理</a>\r\n");
      out.write("\t\t\t\t<ul id = \"ulDNoneGoods\" class=\"ulDNone\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"selGoodsServlet?act=sel\" class=\"navM\">查询商品</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/addGoods.jsp\" class=\"navM\">添加商品</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/selGoods.jsp?act=del\" class=\"navM\">删除商品</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/selGoods.jsp?act=upd\" class=\"navM\">修改商品</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"liD\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"navCM\" onmouseover=\"mouseoveTypes('ulDNoneTypes')\" onmouseleave=\"mouseleaveTypes('ulDNoneTypes')\">类型管理</a>\r\n");
      out.write("\t\t\t\t<ul id = \"ulDNoneTypes\"  class=\"ulDNone\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/addTypes.jsp\" class=\"navM\">添加类型</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/delTypes.jsp\" class=\"navM\">删除类型</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/updTypes.jsp\" class=\"navM\">修改类型</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/selTypes.jsp\" class=\"navM\">查询类型</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"liD\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"navCM\" onmouseover=\"mouseoveMessage('ulDNoneUsers')\" onmouseleave=\"mouseleaveMessage('ulDNoneUsers')\">用户管理</a>\r\n");
      out.write("\t\t\t\t<ul id = \"ulDNoneUsers\"  class=\"ulDNone\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/addUsers.jsp\" class=\"navM\">添加用户</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/delUsers.jsp\" class=\"navM\">删除用户</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/updUsers.jsp\" class=\"navM\">修改用户</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/selUsers.jsp\" class=\"navM\">查询用户</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"liD\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"navCM\" onmouseover=\"mouseoveMessage('ulDNoneOrderMs')\" onmouseleave=\"mouseleaveMessage('ulDNoneOrderMs')\">订单管理</a>\r\n");
      out.write("\t\t\t\t<ul id = \"ulDNoneOrderMs\"  class=\"ulDNone\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/addOrderMs.jsp\" class=\"navM\">添加订单</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/delOrderMs.jsp\" class=\"navM\">删除订单</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/updOrderMs.jsp\" class=\"navM\">修改订单</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/selOrderMs.jsp\" class=\"navM\">查询订单</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"liD\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"navCM\" onmouseover=\"mouseoveMessage('ulDNoneNoticeM')\" onmouseleave=\"mouseleaveMessage('ulDNoneNoticeM')\">公告管理</a>\r\n");
      out.write("\t\t\t\t<ul id = \"ulDNoneNoticeM\"  class=\"ulDNone\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin/addNoticeM.jsp\" class=\"navM\">添加公告</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write(" \t<div id=\"content\" class=\"layer clearfix\">\r\n");
      out.write("\t\t<iframe src=\"selGoodsServlet?act=main\" name=\"content\" width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"auto\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\" class=\"layer clearfix\">Copyright @XXXXXXXXXXX</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
