server:
  port: 10010
spring:
  application:
    name: stock-geteway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #和eureka配合，是否开启基于服务名的路由规则
          lower-case-service-id: true #是否小写
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取Eureka Server服务的列表 只读备份，然后缓存在本地。默认每隔30秒会重新获取并更新数据