server:
  port: 8080
#  servlet:
#    context-path: /stock-client
logging:
  level:
    com.stock: debug  #日志级别都为debug
spring:
  application:
    name: stock-service-1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取Eureka Server服务的列表 只读备份，然后缓存在本地。默认每隔30秒会重新获取并更新数据
feign:
  circuitbreaker:
    enabled: true # 开启Feign的熔断功能
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 设置hystrix的超时时间为2000ms 请求在超过1秒后都会返回错误信息，这是因为Hystix的默认超时时长为1