server:
  port: 8081
  #  servlet:
  #    context-path: /stock-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo
    username: root
    password: 123456
  application:
    name: stock-service-2
mybatis:
  type-aliases-package: com.stock.stockservice.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #服务续约(renew)的间隔，默认为30秒
    lease-expiration-duration-in-seconds: 10 #服务失效时间，默认值90秒